### PR TITLE
fix(linux): wire up YaruWindow.onClose with didRequestAppExit()

### PR DESCRIPTION
**Pull request by jpnurmi**
Close: #33

### CODE REVIEW

**Comment by Feichtmeier** [comment]
should I test it with musicpod?

**Comment by Feichtmeier** [comment]
:vulcan_salute: okay, sec

**Comment by jpnurmi** [comment]
```yaml
dependency_overrides:
  yaru_window_linux:
    git:
      url: https://github.com/jpnurmi/yaru_window.dart.git
      ref: linux-app-exit-request
      path: packages/yaru_window_linux
  yaru_window_platform_interface:
    git:
      url: https://github.com/jpnurmi/yaru_window.dart.git
      ref: linux-app-exit-request
      path: packages/yaru_window_platform_interface
```

**Comment by Feichtmeier** [comment]
w00t it works! :) Proof:

Thank you :+1: :muscle: :brain: 

[Bildschirmaufzeichnung vom 2023-06-21, 13-06-54.webm](https://github.com/ubuntu/yaru_window.dart/assets/15329494/44dd5bcb-c820-4204-a699-6aca9173cc6b)

**Review by d-loose — APPROVED** [review]
LGTM :+1:

**Pull request merged**
